export const en = [
  "夢見たこと？",
  "でも今日は、あなたのためにここにいたかった",
  "それで えぇと... 決勝で彼女に勝てるチャンスはあると思った？",
  "あなたが小さい頃, あなたは見ちゃダメだと教わった。たとえば, もしあなたの相手が怒っていたりしても",
  "私は群衆の中でたくさんの人が騒いでいるのが聞こえて、本当に振り向きたかった, けどできなかった",
  "それと、あなたがトロフィーを受け取っているとき、人混みにはたくさんのブーイングがあった",
  "それは彼女は私を誇りに思っていたし、私は観客が私にブーイングをしていないことを知るべきでした。",
  "カウズ、私は何があったのかわからなかった なぜなら あそこはとてもうるさかったから",
  "私は、あなたがバイザーを目にかぶせたとき、彼らがブーイングを始めたとき、あなたが非常に感情的になっているのがわかりました。",
  "メールしてた？タオルの下で何をしていたの？",
  "編み物してた？",
];
export const jp = [
  "Something you dreamed of?",
  "but today I wanted to be here for you",
  "And um... so did you think you had a chance of beating her at the finals?",
  "when you’re little, you’re taught not to look at, like, if your opponent gets angry or anything.",
  "I head a lot of people in the crowd making noises and I really wanted to turn around but I didn't",
  "And when you were receiving the trophy, there was a lot of booing in the crowd.",
  "that she was proud of me and that I should know that the crowd wasn’t booing at me.",
  "‘Cause I couldn’t tell what was going on because it was just so loud in there.",
  "I saw when you pulled the visor over your eyes when they started booing I could see that you were getting very emotional.",
  "Were you texting? What was going on under that towel?",
  "Were you knitting?",
];

// export const en = [
//   "professor",
//   "copy of the hand",
//   "extra",
//   "mean",
//   "meaning",
//   "say",
//   "explain",
//   "louder",
//   "understand",
//   "repeat",
//   "catch",
//   "slowly",
//   "spell",
//   "pronounce",
//   "minute",
//   "Could you come back to me later",
//   "What ~ in English?",
// ];
// export const jp = ["話す", "遊ぶ"];

// Who Dates Whom? 11問
// export const en = [
//   "1 lbs (pounds)",
//   "2 1 foot",
//   "1 inch",
//   "1 dollar",
//   "for a change",
//   "previous",
//   "blind date",
//   "marital experience",
//   "overweight",
//   "woodworking",
//   "physical education (P. E)",
// ];
// export const jp = [
//   "0.454kg",
//   "3m",
//   "2.54cm",
//   "135yen",
//   "趣向を変えて",
//   "以前の",
//   "初対面の男女のデート",
//   "婚姻経験",
//   "太り過ぎの",
//   "木工作業",
//   "体育",
// ];

// // Love & Marriage 29問
// export const en2 = [
//   "pretend",
//   "passion",
//   "to have a point",
//   "comprehension",
//   "realistically",
//   "floating",
//   "infatuation",
//   "diary",
//   "been bugging me",
//   "daydream",
//   "candlelit",
//   "appropriate",
//   "script",
//   "role",
//   "affectionate",
//   "faithful",
//   "unconditionally",
//   "decision",
//   "ecstatic",
//   "qualities",
//   "poem",
//   "giggle",
//   "cost",
//   "bride",
//   "groom",
//   "beliefs",
//   "situation",
//   "make a mistake",
//   "explain",
// ];
// export const jp2 = [
//   "演じる",
//   "情熱",
//   "意味がある・狙いがある",
//   "理解",
//   "現実的に",
//   "〜が浮かぶ",
//   "夢中",
//   "日記",
//   "悩ませる",
//   "空想に耽る",
//   "キャンドルで照らされた明かり",
//   "適切な",
//   "脚本",
//   "役割",
//   "愛情深い",
//   "信頼のおける",
//   "無条件に",
//   "決定",
//   "夢中の",
//   "品・品質",
//   "詩",
//   "くすくす笑う",
//   "費用",
//   "花嫁・新婦",
//   "花婿・新郎",
//   "信念・理念",
//   "状態・状況",
//   "間違える",
//   "説明する",
// ];

// // Who Get the Heart? 20問
// export const en3 = [
//   "donor",
//   "deteriorate",
//   "recipient",
//   "renowned",
//   "inspiration",
//   "dramatically",
//   "bout",
//   "welfare",
//   "classify",
//   "critically",
//   "transplant",
//   "available",
//   "poet",
//   "literature",
//   "steadily",
//   "heart-lung machine",
//   "originate from",
//   "contributions",
//   "bacteriological diseases",
//   "operation",
// ];
// export const jp3 = [
//   "寄付者・ドナー",
//   "悪化する",
//   "提供を受ける人",
//   "有名な",
//   "刺激 [鼓舞]・励み",
//   "著しく",
//   "争い",
//   "福祉",
//   "分類する",
//   "危うく・決定的に",
//   "移植",
//   "利用 [使用] できる・入手できる",
//   "詩人",
//   "文学",
//   "着実に、絶え間なく",
//   "人工心肺装置",
//   "〜が起源である",
//   "寄付",
//   "細菌の病気",
//   "手術",
// ];

// export const en4 = [
//   "embarrassing",
//   "ugly",
//   "relationship",
//   "thoughtful",
//   "relax",
//   "comfortable",
//   "heart",
//   "hurt",
//   "romantic",
//   "releases",
//   "certain",
//   "chemicals",
//   "toward",
//   "cuddle",
//   "stuffed",
//   "fall in love",
// ];
// export const jp4 = [
//   "恥ずかしい",
//   "醜い",
//   "関係",
//   "思慮深い",
//   "のんびりする くつろぐ",
//   "快適",
//   "心臓",
//   "傷つく",
//   "現実離れした",
//   "放出する",
//   "特定の",
//   "化学物質",
//   "〜にむかって",
//   "抱きしめる",
//   "詰めた",
//   "恋に落ちる",
// ];
